# Generated by Django 5.1.4 on 2024-12-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available", models.BooleanField(default=True)),
                ("calories", models.IntegerField()),
                ("protein", models.IntegerField()),
                ("fat", models.IntegerField()),
                ("carbohydrates", models.IntegerField()),
                (
                    "image",
                    models.ImageField(
                        default="menu/<django.db.models.fields.CharField>.jpg",
                        upload_to="menu/",
                    ),
                ),
            ],
        ),
    ]
