# Generated by Django 5.1.4 on 2024-12-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("func", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("items", models.ManyToManyField(to="func.item")),
            ],
        ),
    ]
